"""Synthetic local P2P source API, kept separate from the main.py /orders demo.

Serves the JSON files generated by generate_p2p_synthetic_source.py so the
real ingestion pipeline (ingestion.generic_rest) can pull P2P test data over
plain HTTP, the same way it would pull from a live ERP endpoint. This exists
only to exercise the pipeline when no real P2P source is available yet.
"""

from __future__ import annotations

import json
from pathlib import Path

from fastapi import FastAPI, HTTPException

app = FastAPI(title="Synthetic P2P Source API")

DATA_DIR = Path(__file__).resolve().parents[2] / "exports" / "synthetic" / "p2p"
ENTITIES = {"pr", "po", "asn", "gr", "invoice", "payment"}


def _load(entity: str) -> list[dict]:
    path = DATA_DIR / f"{entity}.json"
    if not path.exists():
        raise HTTPException(
            status_code=404,
            detail=f"No synthetic data for '{entity}'. Run generate_p2p_synthetic_source.py first.",
        )
    return json.loads(path.read_text(encoding="utf-8"))


@app.get("/p2p/{entity}")
def get_entity(entity: str):
    if entity not in ENTITIES:
        raise HTTPException(status_code=404, detail=f"Unknown P2P entity '{entity}'.")
    return _load(entity)
